### ISSUE TITLE
Add success,can choose it in chart list, but cannot preview chat with data

### ISSUE THREAD

**Issue by ohmyheartbeat** [whw23/superset-plugin-chart-baidu-map#2]
Superset Version: helm superset chat 0.9.2
![image](https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/03a02770-f820-4f3d-82e6-95e6f9a3b9df)

**Comment by ohmyheartbeat** [comment]
sometime this error
<img width="1393" alt="image" src="https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/87d9e95b-48b5-496d-b9e3-998d0e722dbd">

**Comment by ohmyheartbeat** [comment]
<img width="1091" alt="image" src="https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/65fc9414-0a77-4774-9901-cd7407bbe8be">

**Comment by whw23** [comment]
> Superset Version: helm superset chat 0.9.2 ![image](https://user-images.githubusercontent.com/31534021/255086668-03a02770-f820-4f3d-82e6-95e6f9a3b9df.png)

你截图一下定制化配置的部分，有个图标颜色也是必填的

**Comment by ohmyheartbeat** [comment]
![image](https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/b10dadb4-5839-4411-8673-3ea17fd2d165)

**Comment by ohmyheartbeat** [comment]
![image](https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/350b0915-ad9d-415f-9fcf-68686687260b)
F5刷新一下又变成这样了

**Comment by whw23** [comment]
> ![image](https://user-images.githubusercontent.com/31534021/255110683-350b0915-ad9d-415f-9fcf-68686687260b.png) F5刷新一下又变成这样了

我没能复现您的错误，能看一下您检查查询中的内容吗？
![image](https://github.com/whw23/superset-plugin-chart-baidu-map/assets/58520191/00663aa4-dc7a-4a9e-8a22-ecf911bf47bc)
![image](https://github.com/whw23/superset-plugin-chart-baidu-map/assets/58520191/69436d49-78c7-4833-a94d-9e8b128d66b3)

**Comment by ohmyheartbeat** [comment]
![image](https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/93504626-01bc-4efc-b05d-d4f48d1a1e35)
你好，这是查询SQL

**Comment by whw23** [comment]
> ![image](https://user-images.githubusercontent.com/31534021/255527158-93504626-01bc-4efc-b05d-d4f48d1a1e35.png) 你好，这是查询SQL
![image](https://github.com/whw23/superset-plugin-chart-baidu-map/assets/58520191/aded15c5-fd77-4fa1-acc8-67b232c877a9)

您是否申请了百度地图api，并如图script方式插入/app/superset/templates/tail_js_custom_extra.html文件中？
百度地图api需要应用类别是“浏览器端”，并开放给所有ip访问。
添加百度地图API的script后需要重启supserset

**Comment by ohmyheartbeat** [comment]
<img width="1096" alt="image" src="https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/ae8fc305-2ee8-4c54-8036-b05aea33f36d">
<img width="823" alt="image" src="https://github.com/whw23/superset-plugin-chart-baidu-map/assets/31534021/786db6f2-ee61-42dc-be36-23b905a727fb">

**Comment by ohmyheartbeat** [comment]
我是自己改完源码后打包的镜像

**Comment by whw23** [comment]
> 我是自己改完源码后打包的镜像

在我最近测试中没出现问题。
我怀疑是Superset版本的问题，我用的是2.1.0版本

**Comment by whw23** [comment]
This is a superser version issue. 
Please try newest versions.
I will close this issue.

**Comment by whw23** [comment]
This is a superser version issue. 
Please try newest versions.
I will close this issue.
